const types = {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  DISPLAY_LOGIN: "DISPLAY_LOGIN",
  DISPLAY_REGISTRATION: "DISPLAY_REGISTRATION",
  OPEN_LOGIN_MODAL: "OPEN_LOGIN_MODAL",
  CLOSE_LOGIN_MODAL: "CLOSE_LOGIN_MODAL",
  SEND_MESSAGE: "SEND_MESSAGE",
  HANDLE_AUTH_CHANGE: "HANDLE_AUTH_CHANGE",
  GET_APP_USER: "GET_APP_USER",
  LOGOUT: "LOGOUT",
};

export default types;
