const types = {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  DISPLAY_LOGIN: "DISPLAY_LOGIN",
  DISPLAY_REGISTRATION: "DISPLAY_REGISTRATION",
  OPEN_LOGIN_MODAL: "OPEN_LOGIN_MODAL",
  CLOSE_LOGIN_MODAL: "CLOSE_LOGIN_MODAL",
  SEND_MESSAGE: "SEND_MESSAGE",
  HANDLE_AUTH_CHANGE: "HANDLE_AUTH_CHANGE",
  GET_APP_USER: "GET_APP_USER",
  LOGOUT: "LOGOUT",
  HANDLE_LIST_CHANGE: "HANDLE_LIST_CHANGE",
  ADD_ITEM_TO_LIST: "ADD_ITEM_TO_LIST",
  REMOVE_ITEM_FROM_LIST: "REMOVE_ITEM_FROM_LIST",
  PREPARE_TO_EXCHANGE_ITEM: "PREPARE_TO_EXCHANGE_ITEM",
  EXCHANGE_ITEM: "EXCHANGE_ITEM",
  HANDLE_LIBS_CHANGE: "HANDLE_LIBS_CHANGE",
  ADD_FOOD: "ADD_FOOD",
  MAKE_SENTENCE: "MAKE_SENTENCE",
};

export default types;
